### ISSUE TITLE
Installation instructions in readme

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#184]
Trying "Local installation 2" after failing to get the docker install to work. Working on a fresh ubuntu 20.04 LTS install, I find not all the dependencies are listed. 
The missing dependencies are `ruby-bundler` and `libpq-dev`

Haven't yet tried to set up the postgress account and get the server running, but I think at this point everything is installed.

**Comment by philbarker** [comment]
Also missing (I think), edit .env 
- to set APP_DOMAIN (e.g. to localhost:3000)
- to set the POSTGRESQL_ADDRESS (e.g. to localhost)

**Comment by philbarker** [comment]
And finally, it doesn't seem to work:
```
$ curl localhost:3000
{"message":"Attention: Webpacker can't find application.js in /home/phil/desm/public/packs/manifest.json. Possible causes:\n1. You want to set webpacker.yml value of compile to true for your environment\n   unless you are using the `webpack -w` or the webpack-dev-server.\n2. webpack has not yet re-run to reflect updates.\n3. You have misconfigured Webpacker's config/webpacker.yml file.\n4. Your webpack configuration is not creating a manifest.\nYour manifest contains:\n{\n}\n"}
```

With an error message in the consol that is running rails that:

```
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2022-04-29 10:43:20 +0000
/var/lib/gems/2.7.0/gems/activerecord-6.0.4.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/pg-1.3.5/lib/pg.rb:68: warning: The called method `connect' is defined here
   (3.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by HomepageController#index as */*
  Rendering homepage/index.html.erb within layouts/application
  Rendered homepage/index.html.erb within layouts/application (Duration: 9.7ms | Allocations: 284)
The resolved_paths option has been deprecated. Use additional_paths instead.
[Webpacker] Compiling...
[Webpacker] Compilation failed:
yarn run v1.22.18
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


error Command "webpack" not found.

The resolved_paths option has been deprecated. Use additional_paths instead.
Completed 500 Internal Server Error in 31358ms (Views: 1.1ms | ActiveRecord: 0.0ms | Allocations: 1028665)
```

**Comment by excelsior** [comment]
@philbarker Did you run `yarn install` before starting the server?

BTW, I updated the README with more detailed instructions: https://github.com/t3-innovation-network/desm/tree/fix/installation-instuctions

I can create a step-by-step guide specifically for Ubuntu, if you'd like.

**Comment by philbarker** [comment]
> Did you run yarn install before starting the server?

If it was in the instructions I probably did it, but that was nearly a year ago so I don't remember.

I will try with the new instructions and let you know how I get on.

**Comment by philbarker** [comment]
Tried it again, still no luck. 

I followed the instructions for local installation, got all the dependencies updated and as far as "2. Create a database user" and got stuck (I don't use postgres much) and decided to try the docker. Got through the instructions but in then got "This site can’t be reached" as before. No obvious error messages, here are the messages:

$ docker compose up
> [+] Running 4/4
 ⠿ Container desm-redis-1    Created                                                           0.0s
 ⠿ Container desm-webpack-1  Recreated                                                         2.1s
 ⠿ Container desm-db-1       Created                                                           0.0s
 ⠿ Container desm-web-1      Recreated                                                         2.1s
Attaching to desm-db-1, desm-redis-1, desm-web-1, desm-webpack-1
desm-redis-1    | 1:C 17 Mar 2023 16:03:02.846 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
desm-redis-1    | 1:C 17 Mar 2023 16:03:02.857 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
desm-redis-1    | 1:C 17 Mar 2023 16:03:02.857 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
desm-redis-1    | 1:M 17 Mar 2023 16:03:02.859 * Running mode=standalone, port=6379.
desm-redis-1    | 1:M 17 Mar 2023 16:03:02.859 # Server initialized
desm-redis-1    | 1:M 17 Mar 2023 16:03:02.859 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
desm-redis-1    | 1:M 17 Mar 2023 16:03:02.896 * DB loaded from disk: 0.037 seconds
desm-redis-1    | 1:M 17 Mar 2023 16:03:02.896 * Ready to accept connections
desm-webpack-1  | bash: Admin: command not found
desm-webpack-1 exited with code 127
desm-db-1       | 
desm-db-1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
desm-db-1       | 
desm-db-1       | 2023-03-17 16:03:10.541 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
desm-db-1       | 2023-03-17 16:03:10.566 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
desm-db-1       | 2023-03-17 16:03:10.566 UTC [1] LOG:  listening on IPv6 address "::", port 5432
desm-db-1       | 2023-03-17 16:03:10.777 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
desm-db-1       | 2023-03-17 16:03:10.955 UTC [26] LOG:  database system was shut down at 2022-09-23 13:38:35 UTC
desm-db-1       | 2023-03-17 16:03:11.429 UTC [1] LOG:  database system is ready to accept connections
desm-web-1      | Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.3.14). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.14`.
desm-web-1      | => Booting Puma
desm-web-1      | => Rails 6.0.4.7 application starting in development 
desm-web-1      | => Run `rails server --help` for more startup options
desm-web-1      | Puma starting in single mode...
desm-web-1      | * Version 4.3.12 (ruby 2.7.1-p83), codename: Mysterious Traveller
desm-web-1      | * Min threads: 5, max threads: 5
desm-web-1      | * Environment: development
desm-web-1      | * Listening on tcp://0.0.0.0:3030
desm-web-1      | Use Ctrl-C to stop
desm-db-1       | 2023-03-17 16:04:18.998 UTC [35] ERROR:  database "desm_development" already exists
desm-db-1       | 2023-03-17 16:04:18.998 UTC [35] STATEMENT:  CREATE DATABASE "desm_development" ENCODING = 'unicode'
desm-db-1       | 2023-03-17 16:04:19.056 UTC [36] ERROR:  database "desm_development" already exists
desm-db-1       | 2023-03-17 16:04:19.056 UTC [36] STATEMENT:  CREATE DATABASE "desm_development" ENCODING = 'unicode'


and 

$ docker compose run --rm web rake db:create db:migrate db:seed

>  [+] Running 2/0
>  ⠿ Container desm-redis-1  Running                                               0.0s
>  ⠿ Container desm-db-1     Running                                               0.0s
> /usr/local/bundle/gems/activerecord-6.0.4.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
> /usr/local/bundle/gems/pg-1.3.5/lib/pg.rb:68: warning: The called method `connect' is defined here
> Database 'desm_development' already exists
> Database 'desm_development' already exists
> 
>  == Seed from /app/db/fixtures/1.admin.rb
>  - User {:fullname=>"admin", :email=>"admin@desmsolutions.org", :password=>"t3admin", :skip_sending_welcome_email=>true}
> 
> > == Seed from /app/db/fixtures/2.roles.rb
>  - Role {:name=>"Super Admin"}
>  - Role {:name=>"Mapper"}
>  - Role {:name=>"DSO Admin"}
>  - Role {:name=>"Profile Admin"}
> 
> > == Seed from /app/db/fixtures/3.assignments.rb
>  - Assignment {:user=>#<User id: 1, email: "admin@desmsolutions.org", fullname: "admin", password_digest: "$2a$12$jJ0W3RtV5yX1u4foPbbav.RHrJEdonmYZNkMK8Dw6UA...", created_at: "2022-09-23 13:30:01", updated_at: "2023-03-17 16:08:48", organization_id: nil, reset_password_token: nil, reset_password_sent_at: nil, phone: nil, github_handle: nil>, :role=>#<Role id: 1, name: "super admin", created_at: "2022-09-23 13:30:02", updated_at: "2022-09-23 13:30:02">}
> 
> > == Seed from /app/db/fixtures/4.configuration_profile.rb
>  - ConfigurationProfile {:name=>"Test Configuration Profile", :description=>"A 'Configuration Profile' with testing purposes. You can edit this to meet your needs or replace it with a new one.", :administrator=>#<User id: 1, email: "admin@desmsolutions.org", fullname: "admin", password_digest: "$2a$12$jJ0W3RtV5yX1u4foPbbav.RHrJEdonmYZNkMK8Dw6UA...", created_at: "2022-09-23 13:30:01", updated_at: "2023-03-17 16:08:48", organization_id: nil, reset_password_token: nil, reset_password_sent_at: nil, phone: nil, github_handle: nil>, :structure=>{"name"=>"Medical", "description"=>"This configuration profile is meant to hold mapping of specification related to the education area, with domains like student, organization, grade, etc.", "createdAt"=>"12-18-2020", "updatedAt"=>"12-18-2020", "standardsOrganizations"=>[{"name"=>"Credential Registry", "description"=>"A description that provides consistent information about the standards organization", "homepageURL"=>"https://example.dso.url", "standardsPage"=>"https://example.dso.standards-pageurl", "email"=>"info@dso.com", "dsoAdministrator"=>{"fullname"=>"CredReg Admin", "email"=>"admin@credreg.com", "phone"=>"(123) 321-1234"}, "dsoAgents"=>[{"fullname"=>"Mapper N1", "email"=>"mapper1@credreg.com", "phone"=>"(123) 321-1235"}, {"fullname"=>"Mapper N2", "email"=>"mapper2@credreg.com", "phone"=>"(123) 321-1236"}, {"fullname"=>"Mapper N3", "email"=>"mapper3@credreg.com", "phone"=>"(123) 321-1237"}], "associatedSchemas"=>[{"name"=>"SChema file 1", "description"=>"A detailed description of the schema file. E.g. what it represents, which concepts should be expected it to contain.", "origin"=>"https://credreg.net/ctdl/schema/encoding/json", "associatedAbstractClass"=>"http://desm.org/concepts/organization"}, {"name"=>"SChema file 2", "description"=>"A detailed description of the schema file. E.g. what it represents, which concepts should be expected it to contain.", "origin"=>"https://schema.org/version/latest/schemaorg-current-https.jsonld", "associatedAbstractClass"=>"http://desm.org/concepts/credential", "associatedConceptSchemes"=>[{"name"=>"Learning Method", "version"=>"1", "description"=>"A description what the skos file represents.", "origin"=>"https://credreg.net/ctdl/terms/LearningMethod/json?releaseID=20210528"}, {"name"=>"Organization Type", "version"=>"1", "description"=>"A description what the skos file represents.", "origin"=>"https://credreg.net/ctdl/terms/OrganizationType/json?releaseID=20210528"}, {"name"=>"Assessment Method", "version"=>"1", "description"=>"A description what the skos file represents.", "origin"=>"https://credreg.net/ctdl/terms/AssessmentMethod/json?releaseID=20210528"}]}]}], "abstractClasses"=>{"name"=>"The name of the skos file.", "version"=>"1", "description"=>"A description what the skos file represents.", "origin"=>"https://credreg.net/ctdl/terms/Audience/json?releaseID=20210528"}, "mappingPredicates"=>{"name"=>"The name of the skos file.", "version"=>"1", "description"=>"A description what the skos file represents.", "origin"=>"https://credreg.net/ctdl/terms/OrganizationType/json?releaseID=20210528"}}, :json_abstract_classes=>{"@context"=>{"id"=>"@id", "type"=>"@type", "dcterms"=>"http://purl.org/dc/terms/", "rdf"=>"http://www.w3.org/1999/02/22-rdf-syntax-ns#", "rdfs"=>"http://www.w3.org/2000/01/rdf-schema#", "skos"=>"http://www.w3.org/2004/02/skos/core#", "xsd"=>"http://www.w3.org/2001/XMLSchema#", "Concept"=>{"@id"=>"skos:Concept"}, "ConceptScheme"=>{"@id"=>"skos:ConceptScheme"}, "created"=>{"@id"=>"dcterms:created", "@type"=>"xsd:date"}, "creator"=>{"@id"=>"dcterms:creator", "@container"=>"@language"}, "description"=>{"@id"=>"dcterms:description", "@container"=>"@language"}, "hasTopConcept"=>{"@id"=>"skos:hasTopConcept", "@type"=>"@id"}, "inScheme"=>{"@id"=>"skos:inScheme", "@type"=>"@id"}, "prefLabel"=>{"@id"=>"skos:prefLabel", "@container"=>"@language"}, "title"=>{"@id"=>"dcterms:title", "@container"=>"@language"}}, "@graph"=>[{"id"=>"http://desm.org/concepts/mappingClasses", "type"=>"skos:ConceptScheme", "title"=>{"en-us"=>"DESM Schema of Abstract Mapping Classes"}, "description"=>{"en-us"=>"This concept scheme identifies the abstract mapping classes used in 2019-2020 to create the T3 DESM schema crosswalks of specifications relevant to the education to work ecosystem."}, "creator"=>{"en-us"=>"T3 Innovation Network (Pilot Project 1: T3 Phase II)"}, "created"=>"2020-01-07", "hasTopConcept"=>["http://desm.org/concepts/person", "http://desm.org/concepts/organization", "http://desm.org/concepts/course", "http://desm.org/concepts/credential", "http://desm.org/concepts/employment", "http://desm.org/concepts/competency", "http://desm.org/concepts/programOfStudy", "http://desm.org/concepts/earnings"]}, {"id"=>"http://desm.org/concepts/concepts/person", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Person"}, "definition"=>{"en-us"=>"A human being regarded as an individual."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/organization", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Organization"}, "definition"=>{"en-us"=>"An organized body of people with a particular purpose."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/course", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Course"}, "definition"=>{"en-us"=>"A sequence of one or more educational events which aims to build knowledge, competence or ability of learners."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/credential", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Credential"}, "definition"=>{"en-us"=>"A qualification, achievement, personal quality, or aspect of a person's background, typically when used to indicate that they are suitable for something."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/employment", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Employment"}, "definition"=>{"en-us"=>"The condition of a person having paid work"}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/competency", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Competency"}, "definition"=>{"en-us"=>"The ability of a person to do something successfully or efficiently."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/programOfStudy", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Program of Study"}, "definition"=>{"en-us"=>"A program of study means any course or grouping of courses prerequisite to or indicative of a degree."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}, {"id"=>"http://desm.org/concepts/earnings", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Earnings"}, "definition"=>{"en-us"=>"Aggregate data on the earnings of persons."}, "inScheme"=>"http://desm.org/concepts/mappingClasses"}]}, :json_mapping_predicates=>{"@context"=>{"id"=>"@id", "type"=>"@type", "dcterms"=>"http://purl.org/dc/terms/", "desm"=>"https://desmsolutions.org/ns/", "rdf"=>"http://www.w3.org/1999/02/22-rdf-syntax-ns#", "rdfs"=>"http://www.w3.org/2000/01/rdf-schema#", "skos"=>"http://www.w3.org/2004/02/skos/core#", "xsd"=>"http://www.w3.org/2001/XMLSchema#", "Concept"=>{"@id"=>"skos:Concept"}, "ConceptScheme"=>{"@id"=>"skos:ConceptScheme"}, "created"=>{"@id"=>"dcterms:created", "@type"=>"xsd:date"}, "creator"=>{"@id"=>"dcterms:creator", "@container"=>"@language"}, "description"=>{"@id"=>"dcterms:description", "@container"=>"@language"}, "hasTopConcept"=>{"@id"=>"skos:hasTopConcept", "@type"=>"@id"}, "inScheme"=>{"@id"=>"skos:inScheme", "@type"=>"@id"}, "prefLabel"=>{"@id"=>"skos:prefLabel", "@container"=>"@language"}, "title"=>{"@id"=>"dcterms:title", "@container"=>"@language"}, "weight"=>{"@id"=>"desm:weight", "@type"=>"xsd:integer"}}, "@graph"=>[{"id"=>"http://desmsolutions.org/concepts/desmMappingPredicates", "type"=>"skos:ConceptScheme", "title"=>{"en-us"=>"DESM Schema Map Tuning Predicates"}, "description"=>{"en-us"=>"This concept scheme identifies the mapping predicates used in the T3 project to cross-walk (map) SDO's specifications used in expressing data in the education-to-employment context."}, "creator"=>{"en-us"=>"T3 Innovation Network (Pilot Project 1: T3 Phase II)"}, "created"=>"2020-01-07", "hasTopConcept"=>["http://desmsolutions.org/concepts/concept", "http://desmsolutions.org/concepts/reworded", "http://desmsolutions.org/concepts/identical", "http://desmsolutions.org/concepts/similar", "http://desmsolutions.org/concepts/notApplicable", "http://desmsolutions.org/concepts/aggregated", "http://desmsolutions.org/concepts/noMatch", "http://desmsolutions.org/concepts/issue", "http://desmsolutions.org/concepts/disaggregated"]}, {"id"=>"http://desmsolutions.org/concepts/identical", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Identical"}, "definition"=>{"en-us"=>"The definition is identical in wording and intent. This does not consider the extent for how the property is used."}, "weight"=>5, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/reworded", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Reworded"}, "definition"=>{"en-us"=>"The definition is identical in intent, with wording differences."}, "weight"=>5, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/similar", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Similar"}, "definition"=>{"en-us"=>"The definition is similar in intent, but with wording differences."}, "weight"=>4, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/aggregated", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Aggregated"}, "definition"=>{"en-us"=>"Single property in the spine maps to multiple properties in the specification being mapped."}, "weight"=>3, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/disaggregated", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Disaggregated"}, "definition"=>{"en-us"=>"Multiple properties in the spine, map to the property in the specification being mapped."}, "weight"=>3, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/concept", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Concept"}, "definition"=>{"en-us"=>"The definition is related only at a conceptual level, with differences in the intention."}, "weight"=>2, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/noMatch", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"No Match"}, "definition"=>{"en-us"=>"There's no property to match to the property of a class in the spine."}, "weight"=>0, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/notApplicable", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Not Applicable"}, "definition"=>{"en-us"=>"The specification does not include the class with properties in the context of this mapping."}, "weight"=>0, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}, {"id"=>"http://desmsolutions.org/concepts/concepts/issue", "type"=>"skos:Concept", "prefLabel"=>{"en-us"=>"Issue"}, "weight"=>1, "definition"=>{"en-us"=>"Annotation to explain alignment where necessary to clarify or to interpret the mapping."}, "inScheme"=>"http://desmsolutions.org/concepts/desmMappingPredicates"}]}}
> 
> == Seed from /app/db/fixtures/5.basic_terms.rb

**Comment by philbarker** [comment]
Jeanne reports that someone else has been able to set up an instance, so I will close this as being a problem with my system.
