### ISSUE TITLE
Synthetic Spine Needs to Correctly Identify Each Data Standard

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#334]
Currently as properties are added to the spine by a mapper, only the original schema name shows with all properties in the spine.  The correct source schema name needs to be maintained with each property.

**Comment by jeannekitchens** [comment]
@jbaird123 the pilot test mapping synthetic spine consists of properties from multiple schemas. However schema.org was the 1st to be mapped and every property in the spine shows as schema. org.  The spine needs to include the name of the schema from where the property originated.  As an example, the highlighted spine properties are CTDL not schema.org.  If you log in a a DESM pilot mapper, you'll see this issue. 

![image](https://user-images.githubusercontent.com/20917206/200641024-a1afde32-f77d-4de4-a83a-ce2437db890c.png)

**Comment by jbaird123** [comment]
Resolved.

**Comment by angelajubinvilleqip** [comment]
This issue is still occurring. I logged in as CEDS and saw all three spines uploaded, and the origin for each is listed as "CEDS". However, only the "Competence" domain origin is CEDS. 

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/88741604/203607240-073ee6d1-393d-4d04-9aea-308f10a412cf.png">

![Screen Shot 2022-11-23 at 12 08 44 PM](https://user-images.githubusercontent.com/88741604/203607557-9c6c0922-9be8-443c-9c1e-24f88bb3bb50.png)

**Comment by jbaird123** [comment]
@excelsior - Please look into this.

**Comment by jbaird123** [comment]
Resolved. Please reopen if the issue persists.
